// <!-- // ARRAY OF OBJECT -->


// [3,5,4,6,7,8]
// {
//     name:"rishi"
// }
//  [
//  {
//     key:"value",
//     age:21
//  },{
//     name:"rishika"
//  },{
//     key:"value"
//  }
 
//  ]


// MAP : IT RETURNS NEW ARRAY , it take function 
//e==> event (good practice)(can take any alphabet but its good to use e)

// let a=[3,5,6,7,8,10]
// let ans=a.map((e)=>e*2
//     // return e*2

// )
// console.log(ans);


// FILTER METHOD:=> it will filter the particular things(eg->even no,greater than 5),it will take func parameter and it also return the new array.


// let a=[3,5,6,7,8,10]
// let ans=a.filter((e)=>{
//     return e>5;
// })
// console.log(ans);


// FOR EACH:= work like both map , filter but returns in the string format
let a=[3,5,6,7,8,10]
let ans=a.forEach((e)=>
{
console.log(e*2);
})





