function rishi()
{
//    alert("this is an alert msg")
//    let abc= confirm("are you ok")
//   console.log(abc);
//  let hello= prompt("you happy with our website")

//  alert("yes i am "+hello)
//  console.log(hello);

 
 // -----------------------------CHECKING NUMBER IS EVEN OR ODD :--------------------------
   let a= prompt("enter the number")
 if(a%2==0)
  alert("even no")

else
 alert("odd no")
//--------------------------------ADDITION OF TWO NUMBERS--------------------------------------
//  let a= parseInt(prompt("enter no 1:-"));
//  let b= Number(prompt("enter no 2 :-"));
//  let sum=a+b;
//  alert(sum);
 //-----------------------------CAN VOTE / CANT VOTE----------------------------------------
// let a=(prompt("enter the age"));
// if(a>=18)
//     alert("you can vote")
// else
// alert("you cant vote")
//----------------------------SAME QUESTION USING TERNARY OPERATOR-------------------------
//condition ? "on true": "on false":
//let a=(prompt("enter the age:-"));
//a>=18 ? alert("you can vote"): alert("you cant vote")

//---------------------------website------------------------------------------
// let a=confirm("do you like our website")
// alert("thanks")
// let b=confirm("do you like our website")
// alert("sorry")
// ====================================== 1 to  10 counting================================
// let i;
// for(i=1;i<=10;++i)
//     console.log(i)

//=====================================QUE-2 course completion=============================
// if(confirm("have you completed the course "))
// if(confirm("have you done certifiaction"))
//   alert("completed")
// else{
//   alert("not completed")
// }


// ====================================que=4 MARKS ABOVE 33===================
//let marks=parseFloat(prompt("enter the marks"))
// if(marks>=33)
//   alert("pass")
// else{
//   alert("fail")
// }



// =======================================QUE-6 DELETE===============================
// if(confirm("are you sure"))
//   alert("item deleted")
// else{
//   alert("cancellled")
// }

//=======================================que-7==================================
// let n=prompt("enter the number");
// if(n>=0)
//   alert("positive")
// else{
//   alert("negative")
// }



//===================================que-8=================================
// let n=1;
// while(n<=10)
// {
//   console.log(n)
// }


//================================QUE=9==================================
// let ans;
// do{
//    ans=parseInt(prompt("enter the number"))
// }
//    while(ans<=10)
  
}



// ====================================que=10===============================
// let day= parseInt(prompt("Enter a number (1 for Monday, 2 for Tuesday, etc.):"));
// switch (day) {
//     case 1:
//         alert("Monday");
//         break;
//     case 2:
//         alert("Tuesday");
//         break;
//     case 3:
//         alert("Wednesday");
//         break;
//     case 4:
//         alert("Thursday");
//         break;
//     case 5:
//         alert("Friday");
//         break;
//     case 6:
//         alert("Saturday");
//         break;
//     case 7:
//         alert("Sunday");
//         break;
//     default:
//         alert("Invalid input!");
// }   


// ====================================que==================================

// let ans=parseFloat(prompt("enter the number"))
// let dis=confirm("do you have coupen")
// if(dis){
//   alert(ans*0.9)

// }
// else{
//   alert(ans)
// }

// }
rishi()
