// function rishi()
// {
//     let change = document.querySelector("#box")
//     change.innerHTML="<h1> Hello cybrom </h1>"
//     change.style.color="green"
// }
// function rishika()
// {
    // let box=document.querySelector("#box2")
    // box.style.backgroundColor="red"
    // // document.body.style.backgroundColor="yellow"
    // box2.style.backgroundImage="url('image.png')"

    
// }
function resetimg()
{
  box2.style.backgroundImage="none" ;
}
