// let okk=(name)=>{
//     document.write("Jujja");
//     document.write(name);
     
// }
// okk();
// --------------------------------------------------------------

// let a=(num)=>{
   
//     document.write(num)
// }

// ------------------------------------------------------------

// let b=(name,age)=>{
//             document.write(hello my name is  ${name} and your age is ${age}) 
// }


// ----------------------------------------------------------

// let c=(name,age)=>{
//             document.write(<h1>hello my name is  ${name} and your age is ${age}</h1>) 
// }

// ---------------------------------------------------------------

// let d=(name,age)=>{
//     document.querySelector("#bold").innerHTML=<h1>hello my name is  ${name} and your age is ${age}</h1>
   
// }

// ----------------------------------------------------------------

// let sub=()=>{
    
//     let inptext= document.querySelector("#inp").value ;
//     alert(hello ${inptext}); 
//  }
 
//  // ----------------------------------------------------------------