//===============================+++++++++   FUNCTIONS   ++++++==================================
//1.) NORMAL FUNCTION



//2.) ANONYMUS FUNCTION
 let gone=function()
 {
     console.log("Anonymus")
 }
 gone()



//3.)  IIFE := IMMEDITELY INVOKE FUNCTION EXPRESSION 



(
    function(){
        console.log("IIFE");
    }
)()


//4.)  ARROW FUNCTION (=>) [also called special type of ANONYMUS FUNCTION]
    let go=()=>{
        console.log("ARROW")
    }
    go()

// VIVA QUE :- (24/1/25) FUNCTION EXPRESSION AND FUNCTION DECLARATION