// let obj={
//     name:"rishika",
//     age:"21",
//     city:"vidisha",
//     // city:"vidisha"
//     Games:["badminton","circket","hockey"],
//     cybrom:function()
//     {
//         console.log(`hello ${this.age}`);
//     }
    
// }
// console.(arr1[1])
// obj.email="rishika@gmail.com";   //INSERTING THE DATA
// obj.city="bhopal";               //UPDATING THE DATA
// delete obj.city                 //DELETEING THE OBJECT
// console.log(obj)
// obj.cybrom()
// console.log(obj.Games[2])

//object has 2 methods :-
//1. destructring of object :- makes the code clearner and eaisier to read ,allow quickaccess to the properties
//2. spread operator(...)
  

//==================================== DESTRUCURING ========================================

// let students={name:"rishi",
//     age:"21",7
//     city:"bhopal",
//     rollno:"1"
// }
// let{name,age,city,rollno}=students
// console.log(students)


//===================================SPREAD OPERATOR======================================

// const student1 ={name:"rishi",age:"21"}
// const student2={city:"vidisha",grade:"A"}
// const combineStudent={...student1,...student2}
// console.log(combineStudent)

// let arr1=[22,33,44,55]
// let arr2=[56,45,66,77]
// let combine=[...arr1,...arr2]
// console.log(combine)



